version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Istanbul"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      development-tools:
        dependency-type: "development"
        patterns:
          - "friendsofphp/php-cs-fixer"
          - "phpstan/*"
          - "phpunit/*"
